# Generated by Django 3.2 on 2022-10-24 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default='1109', max_length=32, verbose_name='书名')),
                ('title', models.CharField(max_length=32, verbose_name='书名')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('class_name', models.CharField(max_length=32, verbose_name='分类')),
                ('ISBN', models.CharField(max_length=32, verbose_name='条形码')),
                ('publish', models.CharField(max_length=32, verbose_name='出版社')),
                ('borrow_times', models.IntegerField(blank=True, null=True, verbose_name='借阅次数')),
                ('borrow_state', models.SmallIntegerField(choices=[(1, '未借出'), (2, '已借出')], verbose_name='借阅状态')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名称')),
                ('major', models.CharField(max_length=32, verbose_name='专业')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('borrow_date', models.DateTimeField(verbose_name='借出时间')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('character', models.CharField(max_length=32, verbose_name='操作')),
                ('state', models.SmallIntegerField(choices=[(1, '已归还'), (2, '为归还')], verbose_name='状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.book', verbose_name='书名')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.reader', verbose_name='借阅人')),
            ],
        ),
    ]
