# Generated by Django 4.1.2 on 2022-10-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_state',
            field=models.SmallIntegerField(choices=[(1, '在馆'), (2, '已借出')], verbose_name='借阅状态'),
        ),
        migrations.AlterField(
            model_name='record',
            name='character',
            field=models.CharField(max_length=32, verbose_name='属性'),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.SmallIntegerField(choices=[(1, '已归还'), (2, '未归还')], verbose_name='状态'),
        ),
    ]
